export const stock = [
	{
		id: 1,
		nombre: 'Atari (Atari, 1977)',
		desc: 'The Atari 2600, branded as the Atari Video Computer System until November 1982, is a home video game console developed and produced by Atari, Inc',
		precio: '100',
		img: 'https://img.huffingtonpost.com/asset/5c8a40fa36000006186b3b5c.jpeg?ops=scalefit_950_800_noupscale',
		stock: 5,
		categoria: 'consolas',
	},
	{
		id: 2,
		nombre: 'Pc Engine (Nec, 1987)',
		desc: 'The PC Engine (PCエンジン) is a video game console originally released by NEC in Japan in October 1987',
		precio: '200',
		img: 'https://img.huffingtonpost.com/asset/5c8a40fc230000040122db8d.jpeg?ops=scalefit_950_800_noupscale',
		stock: 5,
		categoria: 'consolas',
	},
	{
		id: 3,
		nombre: 'Sega Genesis (Sega, 1989)',
		desc: 'The Genesis was Segas third console and the successor to the Master System. Sega released it in 1988 in Japan as the Mega Drive',
		precio: '300',
		img: 'https://img.huffingtonpost.com/asset/5c8a40fd2300007f0122db8f.jpeg?ops=scalefit_950_800_noupscale',
		stock: 5,
		categoria: 'consolas',
	},
	{
		id: 4,
		nombre: 'Famicom (Nintendo, 1983)',
		desc: 'It was first released as the Family Computer (FC), commonly known as the Famicom, in 1983 in Japan.',
		precio: '400',
		img: 'https://img.huffingtonpost.com/asset/5c8a40fb250000e203c8cc1a.jpeg?ops=scalefit_950_800_noupscale',
		stock: 5,
		categoria: 'consolas',
	},
	{
		id: 5,
		nombre: 'Nintendo 64 (Nintendo, 1996)',
		desc: 'The Nintendo 64 (abbreviated as N64) is a home video game console developed by Nintendo. The successor to the Super Nintendo Entertainment System',
		precio: '500',
		img: 'https://img.huffingtonpost.com/asset/5c8a40ff2500000d04c8cc1c.jpeg?ops=scalefit_950_800_noupscale',
		stock: 5,
		categoria: 'consolas',
	},

	{
		id: 6,
		nombre: 'Castlevania (Capcom, 1986)',
		desc: 'Castlevania is a 1986 action-adventure game developed by Capcom and published by Square for the Nintendo Entertainment System',
		precio: '10',
		img: 'http://deusexmachina.es/wp-content/uploads/2013/02/1234.jpg',
		stock: 5,
		categoria: 'cartuchos',
	},
	{
		id: 7,
		nombre: 'Bubsy (Accolade, 1992)',
		desc: 'Bubsy is a 1992 arcade game developed by Accolade and published by Atari',
		precio: '20',
		img: 'http://deusexmachina.es/wp-content/uploads/2013/01/3344444.jpg',
		stock: 5,
		categoria: 'cartuchos',
	},
	{
		id: 8,
		nombre: 'Super Street Fighter II Turbo (Capcom, 1995)',
		desc: 'Super Street Fighter II Turbo is a 1995 fighting game developed by Capcom and published by Square for the Nintendo Entertainment System',
		precio: '30',
		img: 'http://deusexmachina.es/wp-content/uploads/2013/01/abc.jpg',
		stock: 5,
		categoria: 'cartuchos',
	},
	{
		id: 9,
		nombre: 'Microman (Codemasters, 1994)',
		desc: 'Microman is a 1994 fighting game developed by Codemasters and published by Sega',
		precio: '40',
		img: 'http://deusexmachina.es/wp-content/uploads/2013/01/cartusega02.jpg',
		stock: 5,
		categoria: 'cartuchos',
	},
	{
		id: 10,
		nombre: 'Virtua Racing (Sega, 1992)',
		desc: 'Virtua Racing is a 1992 racing game developed by Sega and published by Namco',
		precio: '50',
		img: 'http://deusexmachina.es/wp-content/uploads/2013/01/jl_blog_svp_02.jpg',
		stock: 5,
		categoria: 'cartuchos',
	},

	{
		id: 11,
		nombre: 'Pac-Man Arcade',
		desc: 'Pac-Man Legacy 12-in-1 Arcade',
		precio: '1000',
		img: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6441/6441982_sd.jpg;maxHeight=640;maxWidth=550',
		stock: 5,
		categoria: 'arcades',
	},
	{
		id: 12,
		nombre: 'Terminator Arcade',
		desc: 'Sepia - Terminator Arcade',
		precio: '2000',
		img: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6483/6483270cv11d.jpg;maxHeight=640;maxWidth=550',
		stock: 5,
		categoria: 'arcades',
	},
	{
		id: 13,
		nombre: 'Mortal Kombat Arcade',
		desc: 'Sepia - Mortal Kombat Legacy Arcade',
		precio: '3000',
		img: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6454/6454302_sd.jpg;maxHeight=640;maxWidth=550',
		stock: 5,
		categoria: 'arcades',
	},
	{
		id: 14,
		nombre: 'Turtles in time Arcade',
		desc: 'Sepia - Turtles In Time Arcade',
		precio: '4000',
		img: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6470/6470490cv11d.jpg;maxHeight=640;maxWidth=550',
		stock: 5,
		categoria: 'arcades',
	},
	{
		id: 15,
		nombre: 'Street Fighter Arcade',
		desc: 'Sepia - Street Fighter Legacy Edition',
		precio: '5000',
		img: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6459/6459600_rd.jpg;maxHeight=640;maxWidth=550',
		stock: 5,
		categoria: 'arcades',
	},
];
